# Generated by Django 2.1.3 on 2018-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_light_lightsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='lightSetting',
            field=models.IntegerField(default=0),
        ),
    ]
