# Generated by Django 2.1.4 on 2018-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181206_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
