# Generated by Django 2.1.4 on 2018-12-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181211_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='light_id',
            field=models.IntegerField(default=0),
        ),
    ]
